# Data Cleaning con Pandas

> Pandas es una librería de Python escrita como extensión de NumPy para manipulación y análisis de datos.

Sitio oficial: [pandas.python.org](https://pandas.pydata.org/)
Documentación Oficial: [pandas.pydata.org/pandas-docs/stable/](https://pandas.pydata.org/pandas-docs/stable/)

En la sesión **Data Cleaning**, utilizaremos principalmente conjuntos de datos de tamaño pequeño o mediano. Un flujo de trabajo común consiste en leer el conjunto de datos, generalmente desde un archivo externo, y luego comenzar a limpiarlo y manipularlo para su análisis.

In [1]:
import pandas as pd

## Cargando e indexando un DataFrame

En esta lección, demostraré cómo cargar datos desde un archivo CSV a un DataFrame.

Cualquier programa de hojas de cálculo pueden guardar o exportar sus resultados en formato CSV (archivo de valores separados por comas). Es un formato bastante flexible, increíblemente ligero y totalmente omnipresente.

### Ejemplo 1

In [2]:
df = pd.read_csv('../data/admission-predict.csv')

df.head()

,Serial No.,GRE Score,TOEFL Score,University Rating,SOP,LOR,CGPA,Research,Chance of Admit
0,1,337,118,4,4.5,4.5,9.65,1,0.92
1,2,324,107,4,4.0,4.5,8.87,1,0.76
2,3,316,104,3,3.0,3.5,8.00,1,0.72
3,4,322,110,3,3.5,2.5,8.67,1,0.80
4,5,314,103,2,2.0,3.0,8.21,0,0.65

Observamos que, por defecto, el índice comienza en 0, mientras que el número de serie de los estudiantes comienza en 1. Por lo tanto, vemos que Pandas ha creado un nuevo índice.

Podemos establecer que la columna `Serial No.` se establezca como índice utilizando la sentencia `index_col`.

In [3]:
df = pd.read_csv('../data/admission-predict.csv', index_col=0)

df.head()

,GRE Score,TOEFL Score,University Rating,SOP,LOR,CGPA,Research,Chance of Admit
Serial No.,,,,,,,,
1,337,118,4,4.5,4.5,9.65,1,0.92
2,324,107,4,4.0,4.5,8.87,1,0.76
3,316,104,3,3.0,3.5,8.00,1,0.72
4,322,110,3,3.5,2.5,8.67,1,0.80
5,314,103,2,2.0,3.0,8.21,0,0.65

In [4]:
# Podemos usar el atributo columns del dataframe para obtener una lista.
df.columns

Index(['GRE Score', 'TOEFL Score', 'University Rating', 'SOP', 'LOR ', 'CGPA',
       'Research', 'Chance of Admit '],
      dtype='object')

Observaciones:

- Las columnas "LOR " y "Chance of Admit." tienen espacios en blanco al final.
- Tenemos dos columnas, "SOP" y "LOR " que probablemente no todos sepan qué significan.

1. Para eliminar los espacios en blanco podemos crear una función que realice la limpieza y luego indicarle a `rename` que la aplique a todos los datos. Python incluye una práctica función de cadena llamada `strip()` para eliminar espacios en blanco. Al pasar esta función a `rename`, la pasamos como parámetro del `mapper` y luego indicamos si el eje debe ser columnas o índice

In [5]:
# Eliminamos los espacios en blanco al final del nombre de las columnas
df = df.rename(mapper=str.strip, axis='columns')

df.columns

Index(['GRE Score', 'TOEFL Score', 'University Rating', 'SOP', 'LOR', 'CGPA',
       'Research', 'Chance of Admit'],
      dtype='object')

2. Ahora vamos a cambiar los nombres de nuestras columnas para que sea más claro. En Pandas, podemos usar la función `rename()`. Esta función recibe un parámetro llamado `columns`, al cual debemos pasarle un diccionario donde las claves sean los nombres de las columnas antiguas y los valores sean los nombres de las nuevas columnas nuevas.

In [6]:
df = df.rename(columns={'SOP': 'Statement of Purpose',
                        'LOR': 'Letter of Recommendation'})
df.columns

Index(['GRE Score', 'TOEFL Score', 'University Rating', 'Statement of Purpose',
       'Letter of Recommendation', 'CGPA', 'Research', 'Chance of Admit'],
      dtype='object')

In [7]:
df.head()

,GRE Score,TOEFL Score,University Rating,Statement of Purpose,Letter of Recommendation,CGPA,Research,Chance of Admit
Serial No.,,,,,,,,
1,337,118,4,4.5,4.5,9.65,1,0.92
2,324,107,4,4.0,4.5,8.87,1,0.76
3,316,104,3,3.0,3.5,8.00,1,0.72
4,322,110,3,3.5,2.5,8.67,1,0.80
5,314,103,2,2.0,3.0,8.21,0,0.65

### Ejemplo 2

También podemos usar el atributo `df.columns` asignándole una lista de nombres de columna, lo que renombrará directamente las columnas.

Esto es muy eficiente, especialmente cuando se tienen muchas columnas y solo se desea cambiar unas pocas. Esta técnica tampoco se ve afectada por errores sutiles en los nombres de las columnas, un problema que acabamos de encontrar. Con una lista, se puede usar el índice para cambiar un valor específico o usar la comprensión de lista para cambiar todos los valores.

In [8]:
# Cargamos nuevamente el archivo original
df = pd.read_csv('../data/admission-predict.csv')

df.head()

,Serial No.,GRE Score,TOEFL Score,University Rating,SOP,LOR,CGPA,Research,Chance of Admit
0,1,337,118,4,4.5,4.5,9.65,1,0.92
1,2,324,107,4,4.0,4.5,8.87,1,0.76
2,3,316,104,3,3.0,3.5,8.00,1,0.72
3,4,322,110,3,3.5,2.5,8.67,1,0.80
4,5,314,103,2,2.0,3.0,8.21,0,0.65

In [9]:
df.columns

Index(['Serial No.', 'GRE Score', 'TOEFL Score', 'University Rating', 'SOP',
       'LOR ', 'CGPA', 'Research', 'Chance of Admit '],
      dtype='object')

In [10]:
# Obtenemos una lista de las columnas
cols = list(df.columns)

# Utilizamos list comprehenshion para cambiar los nombres de las columnas
cols = [col.lower().strip().replace(' ', '_') for col in cols]
df.columns = cols

df.columns

Index(['serial_no.', 'gre_score', 'toefl_score', 'university_rating', 'sop',
       'lor', 'cgpa', 'research', 'chance_of_admit'],
      dtype='object')

## Conclusiones:

Con este notebook, aprendiste a importar un archivo CSV a un objeto DataFrame de Pandas y a realizar una limpieza básica de los nombres de las columnas.

Los mecanismos de importación de archivos CSV en pandas ofrecen muchas opciones diferentes, y es fundamental que las conozcas para dominar la manipulación de datos. Una vez que hayas configurado el formato y la estructura de un DataFrame, tendrás una base sólida para realizar otras acciones, como el análisis y el modelado de datos.

También puedes cargar directamente en DataFrames otras fuentes de datos, como páginas web HTML, bases de datos y otros formatos de archivo. Sin embargo, el formato CSV es, con diferencia, el formato de datos más común y es importante saber cómo manipularlo en pandas.