# Data Cleaning con Pandas

> Pandas es una librería de Python escrita como extensión de NumPy para manipulación y análisis de datos.

Sitio oficial: [pandas.python.org](https://pandas.pydata.org/)
Documentación Oficial: [pandas.pydata.org/pandas-docs/stable/](https://pandas.pydata.org/pandas-docs/stable/)

## Valores faltantes

Ya vimos un adelanto de cómo Pandas maneja los valores faltantes usando el tipo `None` y los valores `NaN` de NumPy. Los valores faltantes son bastante comunes en las actividades de limpieza de datos. Pueden deberse a diversas razones, y aquí solo mencionaré algunas.

Por ejemplo, si realizas una encuesta y un participante no contesta una pregunta, el valor faltante es en realidad una omisión. Este tipo de datos faltantes se denomina:

- **Missing at Random** si existen otras variables que podrían usarse para predecir la variable faltante.
- Si no existe relación con otras variables, entonces denominamos a estos datos **Missing Completely at Random (MCAR)**.

Estos son solo dos ejemplos de datos faltantes, y existen muchos más. Por ejemplo, puede que falten datos porque no se recopilaron, ya sea por el proceso responsable de su recopilación, como un investigador, o porque no tendría sentido recopilarlos. Este último ejemplo es muy común al combinar DataFrames de múltiples fuentes, como al combinar una lista de personas de una universidad con una lista de oficinas de la misma (los estudiantes generalmente no tienen oficinas).

Veamos algunas maneras de manejar los datos faltantes en pandas.

In [1]:
import pandas as pd

Pandas es bastante bueno detectando valores faltantes directamente de los formatos de datos subyacentes, como los archivos CSV.

Aunque la mayoría de los valores faltantes suelen tener el formato NaN, NULL, None o N/A, a veces no están etiquetados con tanta claridad.

Por ejemplo, que utilicen el valor 99 en categorías binarias para indicar un valor faltante. La función `read_csv()` de pandas tiene un parámetro llamado `na_values` que nos permite especificar el formato de los valores faltantes. Permite usar escalares, cadenas, listas o diccionarios.

### Ejemplo 1

In [2]:
df = pd.read_csv('../data/class_grades.csv')
df.head(10)

   Prefix  Assignment  Tutorial  Midterm  TakeHome  Final
0       5       57.14     34.09    64.38     51.48  52.50
1       8       95.05    105.49    67.50     99.07  68.33
2       8       83.70     83.17      NaN     63.15  48.89
3       7         NaN       NaN    49.38    105.93  80.56
4       8       91.32     93.64    95.00    107.41  73.89
5       7       95.00     92.58    93.12     97.78  68.06
6       8       95.05    102.99    56.25     99.07  50.00
7       7       72.85     86.85    60.00       NaN  56.11
8       8       84.26     93.10    47.50     18.52  50.83
9       7       90.10     97.55    51.25     88.89  63.61

Podemos usar la función `.isnull()` para crear una máscara booleana de todo el dataframe.

In [3]:
mask = df.isnull()
mask.head(10)

   Prefix  Assignment  Tutorial  Midterm  TakeHome  Final
0   False       False     False    False     False  False
1   False       False     False    False     False  False
2   False       False     False     True     False  False
3   False        True      True    False     False  False
4   False       False     False    False     False  False
5   False       False     False    False     False  False
6   False       False     False    False     False  False
7   False       False     False    False      True  False
8   False       False     False    False     False  False
9   False       False     False    False     False  False

Esto puede ser útil para procesar filas según ciertas columnas de datos.

Otra operación útil es poder eliminar todas las filas que contengan datos faltantes, lo cual se puede hacer con la función `dropna()`.

In [4]:
df.dropna().head(10)

    Prefix  Assignment  Tutorial  Midterm  TakeHome  Final
0        5       57.14     34.09    64.38     51.48  52.50
1        8       95.05    105.49    67.50     99.07  68.33
4        8       91.32     93.64    95.00    107.41  73.89
5        7       95.00     92.58    93.12     97.78  68.06
6        8       95.05    102.99    56.25     99.07  50.00
8        8       84.26     93.10    47.50     18.52  50.83
9        7       90.10     97.55    51.25     88.89  63.61
10       7       80.44     90.20    75.00     91.48  39.72
12       8       97.16    103.71    72.50     93.52  63.33
13       7       91.28     83.53    81.25     99.81  92.22

> Nota: Observa cómo las filas con índices 2, 3, 7 y 11 ya no están.

Una de las funciones útiles de Pandas para trabajar con valores faltantes es la función de relleno, `fillna()`. Esta función acepta un número o parámetros.

Podrías pasar un único valor, llamado escalar, para reemplazar todos los datos faltantes con un solo valor. Si bien esto no aplica en este caso, es un uso bastante común.

Por lo tanto, si quisiéramos rellenar todos los valores faltantes con 0, usaríamos `fillna`.

In [5]:
df.fillna(0, inplace=True)
df.head(10)

   Prefix  Assignment  Tutorial  Midterm  TakeHome  Final
0       5       57.14     34.09    64.38     51.48  52.50
1       8       95.05    105.49    67.50     99.07  68.33
2       8       83.70     83.17     0.00     63.15  48.89
3       7        0.00      0.00    49.38    105.93  80.56
4       8       91.32     93.64    95.00    107.41  73.89
5       7       95.00     92.58    93.12     97.78  68.06
6       8       95.05    102.99    56.25     99.07  50.00
7       7       72.85     86.85    60.00      0.00  56.11
8       8       84.26     93.10    47.50     18.52  50.83
9       7       90.10     97.55    51.25     88.89  63.61

> Tenga en cuenta que el atributo inplace hace que pandas complete los valores en línea y no devuelve una copia del dataframe, sino que modifica el dataframe que tiene.

Además de las reglas que controlan cómo se cargan los valores faltantes, a veces es útil considerar que estos valores contienen información.

### Ejemplo 2

In [6]:
df = pd.read_csv("../data/log.csv")
df.head(20)

          time    user          video  playback position paused  volume
0   1469974424  cheryl     intro.html                  5  False    10.0
1   1469974454  cheryl     intro.html                  6    NaN     NaN
2   1469974544  cheryl     intro.html                  9    NaN     NaN
3   1469974574  cheryl     intro.html                 10    NaN     NaN
4   1469977514     bob     intro.html                  1    NaN     NaN
5   1469977544     bob     intro.html                  1    NaN     NaN
6   1469977574     bob     intro.html                  1    NaN     NaN
7   1469977604     bob     intro.html                  1    NaN     NaN
8   1469974604  cheryl     intro.html                 11    NaN     NaN
9   1469974694  cheryl     intro.html                 14    NaN     NaN
10  1469974724  cheryl     intro.html                 15    NaN     NaN
11  1469974454     sue  advanced.html                 24    NaN     NaN
12  1469974524     sue  advanced.html                 25    NaN     NaN
13  1469974424     sue  advanced.html                 23  False    10.0
14  1469974554     sue  advanced.html                 26    NaN     NaN
15  1469974624     sue  advanced.html                 27    NaN     NaN
16  1469974654     sue  advanced.html                 28    NaN     5.0
17  1469974724     sue  advanced.html                 29    NaN     NaN
18  1469974484  cheryl     intro.html                  7    NaN     NaN
19  1469974514  cheryl     intro.html                  8    NaN     NaN

En estos datos, la primera columna es una marca de tiempo en formato Unix. La siguiente columna contiene el nombre de usuario, seguido de la página web que visita y el vídeo que reproduce. Cada fila del DataFrame indica la posición de reproducción.

Podemos observar que, a medida que la posición de reproducción aumenta en uno, la marca de tiempo aumenta aproximadamente 30 segundos.

Excepto para el usuario Bob! Resulta que Bob ha pausado su reproducción, por lo que, a medida que avanza el tiempo, la posición de reproducción no cambia.

Nótese también la dificultad de extraer esta información de los datos, ya que no están ordenados por marca de tiempo como cabría esperar. Esto es bastante común en sistemas con un alto grado de paralelismo. Hay muchos valores faltantes en las columnas de pausa y volumen. No es eficiente enviar esta información a través de la red si no ha cambiado. Por lo tanto, este sistema en particular simplemente inserta valores nulos en la base de datos si no hay cambios.

En Pandas, podemos ordenar por índice o por valores. Aquí, simplemente convertiremos la marca de tiempo en un índice y luego ordenaremos por índice.

In [7]:
df = df.set_index('time')
df = df.sort_index()
df.head(20)

              user          video  playback position paused  volume
time
1469974424  cheryl     intro.html                  5  False    10.0
1469974424     sue  advanced.html                 23  False    10.0
1469974454  cheryl     intro.html                  6    NaN     NaN
1469974454     sue  advanced.html                 24    NaN     NaN
1469974484  cheryl     intro.html                  7    NaN     NaN
1469974514  cheryl     intro.html                  8    NaN     NaN
1469974524     sue  advanced.html                 25    NaN     NaN
1469974544  cheryl     intro.html                  9    NaN     NaN
1469974554     sue  advanced.html                 26    NaN     NaN
1469974574  cheryl     intro.html                 10    NaN     NaN
1469974604  cheryl     intro.html                 11    NaN     NaN
1469974624     sue  advanced.html                 27    NaN     NaN
1469974634  cheryl     intro.html                 12    NaN     NaN
1469974654     sue  advanced.html                 28    NaN     5.0
1469974664  cheryl     intro.html                 13    NaN     NaN
1469974694  cheryl     intro.html                 14    NaN     NaN
1469974724  cheryl     intro.html                 15    NaN     NaN
1469974724     sue  advanced.html                 29    NaN     NaN
1469974754     sue  advanced.html                 30    NaN     NaN
1469974824     sue  advanced.html                 31    NaN     NaN

Si analizamos detenidamente la salida, observaremos que el índice no es realmente único. Dos usuarios parecen poder usar el sistema simultáneamente. De nuevo, un caso muy común.

Restablezcamos el índice y, en su lugar, usemos indexación multinivel por tiempo y usuario, promoviendo el nombre de usuario a un segundo nivel del índice para solucionar este problema.

In [8]:
df = df.reset_index()
df = df.set_index(['time', 'user'])
df

                           video  playback position paused  volume
time       user
1469974424 cheryl     intro.html                  5  False    10.0
           sue     advanced.html                 23  False    10.0
1469974454 cheryl     intro.html                  6    NaN     NaN
           sue     advanced.html                 24    NaN     NaN
1469974484 cheryl     intro.html                  7    NaN     NaN
1469974514 cheryl     intro.html                  8    NaN     NaN
1469974524 sue     advanced.html                 25    NaN     NaN
1469974544 cheryl     intro.html                  9    NaN     NaN
1469974554 sue     advanced.html                 26    NaN     NaN
1469974574 cheryl     intro.html                 10    NaN     NaN
1469974604 cheryl     intro.html                 11    NaN     NaN
1469974624 sue     advanced.html                 27    NaN     NaN
1469974634 cheryl     intro.html                 12    NaN     NaN
1469974654 sue     advanced.html                 28    NaN     5.0
1469974664 cheryl     intro.html                 13    NaN     NaN
1469974694 cheryl     intro.html                 14    NaN     NaN
1469974724 cheryl     intro.html                 15    NaN     NaN
           sue     advanced.html                 29    NaN     NaN
1469974754 sue     advanced.html                 30    NaN     NaN
1469974824 sue     advanced.html                 31    NaN     NaN
1469974854 sue     advanced.html                 32    NaN     NaN
1469974924 sue     advanced.html                 33    NaN     NaN
1469977424 bob        intro.html                  1   True    10.0
1469977454 bob        intro.html                  1    NaN     NaN
1469977484 bob        intro.html                  1    NaN     NaN
1469977514 bob        intro.html                  1    NaN     NaN
1469977544 bob        intro.html                  1    NaN     NaN
1469977574 bob        intro.html                  1    NaN     NaN
1469977604 bob        intro.html                  1    NaN     NaN
1469977634 bob        intro.html                  1    NaN     NaN
1469977664 bob        intro.html                  1    NaN     NaN
1469977694 bob        intro.html                  1    NaN     NaN
1469977724 bob        intro.html                  1    NaN     NaN

Ahora que tenemos los datos indexados y ordenados correctamente, podemos completar los datos faltantes usando `ffill`.

In [9]:
df = df.fillna(method='ffill')
df.head()

/tmp/ipykernel_1851862/230151708.py:1: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df = df.fillna(method='ffill')
/tmp/ipykernel_1851862/230151708.py:1: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df = df.fillna(method='ffill')

                           video  playback position  paused  volume
time       user
1469974424 cheryl     intro.html                  5   False    10.0
           sue     advanced.html                 23   False    10.0
1469974454 cheryl     intro.html                  6   False    10.0
           sue     advanced.html                 24   False    10.0
1469974484 cheryl     intro.html                  7   False    10.0

### Ejemplo 3

También podemos personalizar el relleno para reemplazar valores con la función `replace()`. Permite el reemplazo mediante varios métodos: valor a valor, lista, diccionario y expresiones regulares.

Generemos un ejemplo sencillo.

In [10]:
df = pd.DataFrame({'A': [1, 1, 2, 3, 4],
                   'B': [3, 6, 3, 8, 9],
                   'C': ['a', 'b', 'c', 'd', 'e']})
df

   A  B  C
0  1  3  a
1  1  6  b
2  2  3  c
3  3  8  d
4  4  9  e

In [11]:
# Reemplazamos valor por valor
df.replace(1, 100)

     A  B  C
0  100  3  a
1  100  6  b
2    2  3  c
3    3  8  d
4    4  9  e

In [12]:
# Reemplazamos valores por lista
df.replace([1, 3], [100, 300])

     A    B  C
0  100  300  a
1  100    6  b
2    2  300  c
3  300    8  d
4    4    9  e

### Ejemplo 4

La función de reemplazo de pandas es que también admite expresiones regulares.

In [13]:
df = pd.read_csv("../data/log.csv")
df.head(20)

          time    user          video  playback position paused  volume
0   1469974424  cheryl     intro.html                  5  False    10.0
1   1469974454  cheryl     intro.html                  6    NaN     NaN
2   1469974544  cheryl     intro.html                  9    NaN     NaN
3   1469974574  cheryl     intro.html                 10    NaN     NaN
4   1469977514     bob     intro.html                  1    NaN     NaN
5   1469977544     bob     intro.html                  1    NaN     NaN
6   1469977574     bob     intro.html                  1    NaN     NaN
7   1469977604     bob     intro.html                  1    NaN     NaN
8   1469974604  cheryl     intro.html                 11    NaN     NaN
9   1469974694  cheryl     intro.html                 14    NaN     NaN
10  1469974724  cheryl     intro.html                 15    NaN     NaN
11  1469974454     sue  advanced.html                 24    NaN     NaN
12  1469974524     sue  advanced.html                 25    NaN     NaN
13  1469974424     sue  advanced.html                 23  False    10.0
14  1469974554     sue  advanced.html                 26    NaN     NaN
15  1469974624     sue  advanced.html                 27    NaN     NaN
16  1469974654     sue  advanced.html                 28    NaN     5.0
17  1469974724     sue  advanced.html                 29    NaN     NaN
18  1469974484  cheryl     intro.html                  7    NaN     NaN
19  1469974514  cheryl     intro.html                  8    NaN     NaN

Para reemplazar usando una expresión regular, definimos:
- el primer parámetro como el patrón que queremos buscar,
- el segundo como el valor que queremos mostrar al encontrar una coincidencia y,
- finalmente, pasamos un tercer parámetro: `regex=True`.

Imagina que queremos detectar todas las páginas HTML en la columna "video" (es decir, las que terminan en ".html") y reemplazarlas con la palabra clave "webpage".

In [14]:
df.replace(to_replace=".*.html$",
           value="webpage",
           regex=True)

          time    user    video  playback position paused  volume
0   1469974424  cheryl  webpage                  5  False    10.0
1   1469974454  cheryl  webpage                  6    NaN     NaN
2   1469974544  cheryl  webpage                  9    NaN     NaN
3   1469974574  cheryl  webpage                 10    NaN     NaN
4   1469977514     bob  webpage                  1    NaN     NaN
5   1469977544     bob  webpage                  1    NaN     NaN
6   1469977574     bob  webpage                  1    NaN     NaN
7   1469977604     bob  webpage                  1    NaN     NaN
8   1469974604  cheryl  webpage                 11    NaN     NaN
9   1469974694  cheryl  webpage                 14    NaN     NaN
10  1469974724  cheryl  webpage                 15    NaN     NaN
11  1469974454     sue  webpage                 24    NaN     NaN
12  1469974524     sue  webpage                 25    NaN     NaN
13  1469974424     sue  webpage                 23  False    10.0
14  1469974554     sue  webpage                 26    NaN     NaN
15  1469974624     sue  webpage                 27    NaN     NaN
16  1469974654     sue  webpage                 28    NaN     5.0
17  1469974724     sue  webpage                 29    NaN     NaN
18  1469974484  cheryl  webpage                  7    NaN     NaN
19  1469974514  cheryl  webpage                  8    NaN     NaN
20  1469974754     sue  webpage                 30    NaN     NaN
21  1469974824     sue  webpage                 31    NaN     NaN
22  1469974854     sue  webpage                 32    NaN     NaN
23  1469974924     sue  webpage                 33    NaN     NaN
24  1469977424     bob  webpage                  1   True    10.0
25  1469977454     bob  webpage                  1    NaN     NaN
26  1469977484     bob  webpage                  1    NaN     NaN
27  1469977634     bob  webpage                  1    NaN     NaN
28  1469977664     bob  webpage                  1    NaN     NaN
29  1469974634  cheryl  webpage                 12    NaN     NaN
30  1469974664  cheryl  webpage                 13    NaN     NaN
31  1469977694     bob  webpage                  1    NaN     NaN
32  1469977724     bob  webpage                  1    NaN     NaN

> Nota:
>
> Una última nota sobre los valores faltantes. Al usar funciones estadísticas en DataFrames, estas funciones suelen ignorar los valores faltantes.
>
> Por ejemplo, si intentas calcular la media de un DataFrame, la función de NumPy ignorará los valores faltantes. Esto suele ser lo que se busca, pero debes tener en cuenta que se están excluyendo valores. El motivo de la presencia de valores faltantes depende del problema que se esté intentando resolver.