# Introducción a Pandas

> Pandas es una librería de Python escrita como extensión de NumPy para manipulación y análisis de datos.

Sitio oficial: [pandas.python.org](https://pandas.pydata.org/)
Documentación Oficial: [pandas.pydata.org/pandas-docs/stable/](https://pandas.pydata.org/pandas-docs/stable/)

## ¿Cómo accedemos a los elementos de un DataFrame?

In [1]:
import pandas as pd

La estructura de datos DataFrame es fundamental en la biblioteca Pandas. Es el objeto principal con el que trabajarás en tareas de análisis y limpieza de datos.

Conceptualmente, un DataFrame es un objeto de serie bidimensional, con un índice y varias columnas de contenido, cada una con una etiqueta.

In [2]:
students = [{'Name': 'Alice', 'Class': 'Physics', 'Score': 85},
            {'Name': 'Jack', 'Class': 'Chemistry', 'Score': 82},
            {'Name': 'Helen', 'Class': 'Biology', 'Score': 90}]

df = pd.DataFrame(students, index=['school1', 'school2', 'school1'])

df.head()

          Name      Class  Score
school1  Alice    Physics     85
school2   Jack  Chemistry     82
school1  Helen    Biology     90

### Accediendo mediante `.loc` y `loc`

Al igual que con las series, podemos extraer datos usando los atributos `.iloc` y `.loc`. Dado que el DataFrame es bidimensional, pasar un solo valor al operador de indexación `loc` devolverá la serie si solo hay una fila.

In [3]:
df.loc['school2']

Name          Jack
Class    Chemistry
Score           82
Name: school2, dtype: object

In [4]:
# Comprobamos el type() devuelto
type(df.loc['school2'])

pandas.core.series.Series

Es importante recordar que los índices y los nombres de las columnas, tanto en el eje horizontal como en el vertical, podrían no ser únicos. En este ejemplo, vemos dos registros para la escuela1 en filas diferentes.

Si usamos un solo valor con el atributo `loc` del DataFrame, se devolverán varias filas del DataFrame, no como una nueva serie, sino como un nuevo DataFrame.

In [5]:
df.loc['school1']

          Name    Class  Score
school1  Alice  Physics     85
school1  Helen  Biology     90

In [6]:
# Comprobamos el type() devuelto
type(df.loc['school1'])

pandas.core.frame.DataFrame

Una de las ventajas del DataFrame de Pandas es que permite seleccionar datos rápidamente según varios ejes.

Por ejemplo, si solo se quisiera listar los nombres de los estudiantes de la `school1`, se proporcionarían dos parámetros a `.loc`: el índice de la fila y el nombre de la columna.

In [7]:
df.loc['school1', 'Name']

school1    Alice
school1    Helen
Name: Name, dtype: object

Recuerdemos que, al igual que con las Series, los desarrolladores de pandas implementaron esto usando el operador de indexación y no como parámetros de una función.

¿Qué haríamos si quisiéramos seleccionar una sola columna? Existen varios mecanismos. Primero, podríamos transponer la matriz. Esto convierte todas las filas en columnas y viceversa, y se realiza con el atributo `T`.

In [8]:
df.T

       school1    school2  school1
Name     Alice       Jack    Helen
Class  Physics  Chemistry  Biology
Score       85         82       90

Entonces podemos llamar a `.loc` de la transpuesta para obtener los nombres de los estudiantes

In [9]:
df.T.loc['Name']

school1    Alice
school2     Jack
school1    Helen
Name: Name, dtype: object

Sin embargo, dado que `iloc` y `loc` se utilizan para la selección de filas, Pandas reserva el operador de indexación directamente en el DataFrame para la selección de columnas. En un DataFrame de Pandas, las columnas siempre tienen un nombre.

Por lo tanto, esta selección siempre se basa en etiquetas y no resulta tan confusa

In [10]:
df['Name']

school1    Alice
school2     Jack
school1    Helen
Name: Name, dtype: object

In [11]:
type(df['Name'])

pandas.core.series.Series

Dado que el resultado de usar el operador de indexación es un DataFrame o una Serie, se pueden encadenar operaciones.

Por ejemplo, podemos seleccionar todas las filas relacionadas con la `school1` usando `.loc`, y luego proyectar la columna `name` solo a partir de esas filas.

In [12]:
df.loc['school1']['Name']

school1    Alice
school1    Helen
Name: Name, dtype: object

In [13]:
# Verificamos el type() devuelto
print(type(df.loc['school1']))  # DataFrame
print(type(df.loc['school1']['Name']))  # Series

<class 'pandas.core.frame.DataFrame'>
<class 'pandas.core.series.Series'>

El atributo `.loc` selecciona filas y puede recibir dos parámetros:
- el índice de la fila y
- la lista de nombres de columna.

El atributo `.loc` también admite el rebanado.

Si quisiéramos seleccionar todas las filas, podemos utilizar dos puntos para indicar un rebanado completo de principio a fin.

Esto es similar a rebanar caracteres en una lista en Python. Luego, podemos agregar el nombre de la columna como segundo parámetro, en forma de cadena. Si quisiéramos incluir varias columnas, podríamos hacerlo en una lista. Pandas devolverá únicamente las columnas solicitadas.

Aquí tienes un ejemplo donde solicitamos los nombres y puntuaciones de todas las escuelas usando el operador `.loc`.

In [14]:
df.loc[:,['Name', 'Score']]

          Name  Score
school1  Alice     85
school2   Jack     82
school1  Helen     90

> Nota: Los dos puntos indican que queremos obtener todas las filas, y la lista en la segunda posición del argumento es la lista de columnas que queremos recuperar.

### Conclusiones:

Aprendimos sobre la estructura de datos que más usarás en pandas: el DataFrame.

El DataFrame se indexa tanto por filas como por columnas, y puedes seleccionar fácilmente filas individuales y proyectar las columnas que te interesen usando los métodos de indexación de la clase Series.