# Data Analysis con Pandas

> Pandas es una librería de Python escrita como extensión de NumPy para manipulación y análisis de datos.

Sitio oficial: [pandas.python.org](https://pandas.pydata.org/)
Documentación Oficial: [pandas.pydata.org/pandas-docs/stable/](https://pandas.pydata.org/pandas-docs

## Tablas Pivot con Pandas

In [1]:
import pandas as pd

Las **tablas pivot** (`pivot_table`) son una herramienta fundamental de Pandas para **resumir datos** en un DataFrame con un propósito específico.

- Las tablas pivot hacen un uso intensivo de las **funciones de agregación**.
- Una tabla pivot es en sí misma un DataFrame, donde las filas representan una variable de interés, las columnas otra, y las celdas contienen algún **valor agregado** (como la media o la suma).
- Una tabla pivot a menudo incluye **valores marginales** (totales generales), los que permiten ver la relación entre dos variables de un vistazo.

### Preparando el Dataset

#### Carga y Exploración del Dataset


Utilizaremos el conjunto de datos de la **Clasificación Mundial de Universidades de Times Higher Education** (Times Higher Education World University Ranking), una de las métricas universitarias más influyentes.

In [2]:
path_to_data = '../data/'
df = pd.read_csv(f'{path_to_data}cwurData.csv')
df

,world_rank,institution,country,national_rank,quality_of_education,alumni_employment,quality_of_faculty,publications,influence,citations,broad_impact,patents,score,year
0,1,Harvard University,USA,1,7,9,1,1,1,1,NaN,5,100.00,2012
1,2,Massachusetts Institute of Technology,USA,2,9,17,3,12,4,4,NaN,1,91.67,2012
2,3,Stanford University,USA,3,17,11,5,4,2,2,NaN,15,89.50,2012
3,4,University of Cambridge,United Kingdom,1,10,24,4,16,16,11,NaN,50,86.17,2012
4,5,California Institute of Technology,USA,4,2,29,7,37,22,22,NaN,18,85.21,2012
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2195,996,University of the Algarve,Portugal,7,367,567,218,926,845,812,969.0,816,44.03,2015
2196,997,Alexandria University,Egypt,4,236,566,218,997,908,645,981.0,871,44.03,2015
2197,998,Federal University of Ceará,Brazil,18,367,549,218,830,823,812,975.0,824,44.03,2015
2198,999,University of A Coruña,Spain,40,367,567,218,886,974,812,975.0,651,44.02,2015
2199,1000,China Pharmaceutical University,China,83,367,567,218,861,991,812,981.0,547,44.02,2015

In [3]:
df.dtypes

world_rank                int64
institution              object
country                  object
national_rank             int64
quality_of_education      int64
alumni_employment         int64
quality_of_faculty        int64
publications              int64
influence                 int64
citations                 int64
broad_impact            float64
patents                   int64
score                   float64
year                      int64
dtype: object

#### Creación de la Columna `Rank_Level`


Antes de crear la tabla pivot, vamos a crear una nueva columna llamada **Rank\_Level** para categorizar las universidades según su `world_rank`:

  * **Primer Nivel:** 1-100
  * **Segundo Nivel:** 101-200
  * **Tercer Nivel:** 201-300
  * **Otras Top Universidades:** \> 300

Definiremos una función para realizar esta clasificación y luego la aplicaremos a la columna `world_rank`.

In [4]:
def create_category(ranking):
    # Como el ranking es un entero, usaremos una serie de sentencias if/elif
    if (ranking >= 1) & (ranking <= 100):
        return "First Tier Top University"
    elif (ranking >= 101) & (ranking <= 200):
        return "Second Tier Top University"
    elif (ranking >= 201) & (ranking <= 300):
        return "Third Tier Top University"
    return "Other Top University"


df['Rank_Level'] = df['world_rank'].apply(lambda x: create_category(x))
df

,world_rank,institution,country,national_rank,quality_of_education,alumni_employment,quality_of_faculty,publications,influence,citations,broad_impact,patents,score,year,Rank_Level
0,1,Harvard University,USA,1,7,9,1,1,1,1,NaN,5,100.00,2012,First Tier Top University
1,2,Massachusetts Institute of Technology,USA,2,9,17,3,12,4,4,NaN,1,91.67,2012,First Tier Top University
2,3,Stanford University,USA,3,17,11,5,4,2,2,NaN,15,89.50,2012,First Tier Top University
3,4,University of Cambridge,United Kingdom,1,10,24,4,16,16,11,NaN,50,86.17,2012,First Tier Top University
4,5,California Institute of Technology,USA,4,2,29,7,37,22,22,NaN,18,85.21,2012,First Tier Top University
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2195,996,University of the Algarve,Portugal,7,367,567,218,926,845,812,969.0,816,44.03,2015,Other Top University
2196,997,Alexandria University,Egypt,4,236,566,218,997,908,645,981.0,871,44.03,2015,Other Top University
2197,998,Federal University of Ceará,Brazil,18,367,549,218,830,823,812,975.0,824,44.03,2015,Other Top University
2198,999,University of A Coruña,Spain,40,367,567,218,886,974,812,975.0,651,44.02,2015,Other Top University
2199,1000,China Pharmaceutical University,China,83,367,567,218,861,991,812,981.0,547,44.02,2015,Other Top University

### Creación de una Tabla Pivot Simple

Una tabla pivot nos permite "pivotar" (girar) una columna para que sus valores se conviertan en nuevos encabezados de columna y compararla con otra columna como índice de fila.


Entonces, vamos a crear una tabla que compare el **nivel de ranking** (`Rank_Level`) de las universidades de cada **país** (`country`), utilizando el promedio (`mean`) del **puntaje general** (`score`) por país.

Para esto, indicamos a Pandas:

  * `values`: la columna a agregar (`score`).
  * `index`: la columna que serán las filas (`country`).
  * `columns`: la columna que serán los encabezados (`Rank_Level`).
  * `aggfunc`: la función de agregación (`mean`).

In [5]:
df.pivot_table(values='score',
               index='country',
               columns='Rank_Level',
               aggfunc='mean')

Rank_Level,First Tier Top University,Other Top University,Second Tier Top University,Third Tier Top University
country,,,,
Argentina,NaN,44.672857,NaN,NaN
Australia,47.942500,44.645750,49.242500,47.285000
Austria,NaN,44.864286,NaN,47.066667
Belgium,51.875000,45.081000,49.084000,46.746667
Brazil,NaN,44.499706,49.565000,NaN
Bulgaria,NaN,44.335000,NaN,NaN
Canada,53.633846,44.760541,49.218182,46.826364
Chile,NaN,44.767500,NaN,NaN
China,53.592500,44.564267,47.868000,46.926250
Colombia,NaN,44.432500,NaN,NaN
Croatia,NaN,44.770000,NaN,NaN
Cyprus,NaN,44.210000,NaN,NaN
Czech Republic,NaN,44.587778,NaN,46.320000
Denmark,49.180000,45.177500,48.965000,NaN
Egypt,NaN,44.230000,NaN,NaN
Estonia,NaN,44.810000,NaN,NaN
Finland,44.415000,45.062500,50.400000,NaN
France,51.914444,44.609028,48.888571,47.125833
Germany,49.153636,44.978305,48.695556,46.910370
Greece,NaN,44.854286,NaN,NaN
Hong Kong,NaN,45.284286,48.625000,47.100000
Hungary,NaN,44.603333,NaN,NaN
Iceland,NaN,44.980000,NaN,NaN
India,NaN,44.713226,NaN,NaN
Iran,NaN,44.270000,NaN,NaN
Ireland,NaN,44.542500,47.845000,46.780000
Israel,56.307143,45.013333,50.005000,NaN
Italy,48.736667,44.964177,48.618000,46.861111
Japan,58.812692,44.641583,49.157143,46.546667
Lebanon,NaN,44.655000,NaN,NaN
Lithuania,NaN,44.355000,NaN,NaN
Malaysia,NaN,45.008333,NaN,NaN
Mexico,NaN,45.102500,NaN,NaN
Netherlands,48.378333,45.163333,49.963636,46.656667
New Zealand,NaN,44.832000,NaN,46.515000
Norway,47.056667,44.950000,50.700000,46.446667
Poland,NaN,44.497222,NaN,NaN
Portugal,NaN,44.717273,NaN,46.480000
Puerto Rico,NaN,44.175000,NaN,NaN
Romania,NaN,44.133333,NaN,NaN
Russia,51.846667,44.462500,NaN,46.520000
Saudi Arabia,NaN,44.511250,NaN,NaN
Serbia,NaN,44.420000,NaN,NaN
Singapore,50.720000,NaN,49.320000,NaN
Slovak Republic,NaN,44.490000,NaN,NaN
Slovenia,NaN,44.615000,NaN,NaN
South Africa,NaN,45.246667,49.575000,46.680000
South Korea,55.990000,44.805714,49.136667,47.490000
Spain,NaN,44.724730,49.310000,46.675000
Sweden,50.672000,45.272500,49.306250,46.456667
Switzerland,54.005000,44.625000,48.184000,47.930000
Taiwan,54.210000,44.476667,NaN,47.065000
Thailand,NaN,44.830000,NaN,46.550000
Turkey,NaN,44.481000,NaN,NaN
USA,61.066726,44.871718,49.069524,46.818333
Uganda,NaN,44.280000,NaN,NaN
United Arab Emirates,NaN,44.220000,NaN,NaN
United Kingdom,63.937931,44.881299,48.957500,46.862273
Uruguay,NaN,44.255000,NaN,NaN

> Observamos un DataFrame donde en el índice (filas) están los paises y las columnas son los niveles en el ranking. Los valores son la **puntuación promedio** para esa combinación de país y nivel de ranking. Los valores **NaN** (Not a Number) indican que no hay observaciones para esa combinación, como en el caso de Argentina, que solo tiene universidades en la categoría "Other Top University".

### Múltiples Funciones de Agregación

Las tablas pivot no se limitan a una única función. Podemos pasar una **lista de funciones** al parámetro `aggfunc`. Pandas proporcionará el resultado utilizando **nombres de columnas jerárquicas** (MultiIndex).

Intentemos la misma consulta, pero agregando también la función `max` (puntuación máxima).

In [6]:
df.pivot_table(values='score',
               index='country',
               columns='Rank_Level',
               aggfunc=['mean', 'max'])

                                          mean                       \
Rank_Level           First Tier Top University Other Top University
country
Argentina                                  NaN            44.672857
Australia                            47.942500            44.645750
Austria                                    NaN            44.864286
Belgium                              51.875000            45.081000
Brazil                                     NaN            44.499706
Bulgaria                                   NaN            44.335000
Canada                               53.633846            44.760541
Chile                                      NaN            44.767500
China                                53.592500            44.564267
Colombia                                   NaN            44.432500
Croatia                                    NaN            44.770000
Cyprus                                     NaN            44.210000
Czech Republic                             NaN            44.587778
Denmark                              49.180000            45.177500
Egypt                                      NaN            44.230000
Estonia                                    NaN            44.810000
Finland                              44.415000            45.062500
France                               51.914444            44.609028
Germany                              49.153636            44.978305
Greece                                     NaN            44.854286
Hong Kong                                  NaN            45.284286
Hungary                                    NaN            44.603333
Iceland                                    NaN            44.980000
India                                      NaN            44.713226
Iran                                       NaN            44.270000
Ireland                                    NaN            44.542500
Israel                               56.307143            45.013333
Italy                                48.736667            44.964177
Japan                                58.812692            44.641583
Lebanon                                    NaN            44.655000
Lithuania                                  NaN            44.355000
Malaysia                                   NaN            45.008333
Mexico                                     NaN            45.102500
Netherlands                          48.378333            45.163333
New Zealand                                NaN            44.832000
Norway                               47.056667            44.950000
Poland                                     NaN            44.497222
Portugal                                   NaN            44.717273
Puerto Rico                                NaN            44.175000
Romania                                    NaN            44.133333
Russia                               51.846667            44.462500
Saudi Arabia                               NaN            44.511250
Serbia                                     NaN            44.420000
Singapore                            50.720000                  NaN
Slovak Republic                            NaN            44.490000
Slovenia                                   NaN            44.615000
South Africa                               NaN            45.246667
South Korea                          55.990000            44.805714
Spain                                      NaN            44.724730
Sweden                               50.672000            45.272500
Switzerland                          54.005000            44.625000
Taiwan                               54.210000            44.476667
Thailand                                   NaN            44.830000
Turkey                                     NaN            44.481000
USA                                  61.066726            44.871718
Uganda                                     NaN            44.280000
United Arab Emirates                       NaN            44.220000
United Kingdom                       63.937931            44.881299
Uruguay                                    NaN            44.255000

                                                                           \
Rank_Level           Second Tier Top University Third Tier Top University
country
Argentina                                   NaN                       NaN
Australia                             49.242500                 47.285000
Austria                                     NaN                 47.066667
Belgium                               49.084000                 46.746667
Brazil                                49.565000                       NaN
Bulgaria                                    NaN                       NaN
Canada                                49.218182                 46.826364
Chile                                       NaN                       NaN
China                                 47.868000                 46.926250
Colombia                                    NaN                       NaN
Croatia                                     NaN                       NaN
Cyprus                                      NaN                       NaN
Czech Republic                              NaN                 46.320000
Denmark                               48.965000                       NaN
Egypt                                       NaN                       NaN
Estonia                                     NaN                       NaN
Finland                               50.400000                       NaN
France                                48.888571                 47.125833
Germany                               48.695556                 46.910370
Greece                                      NaN                       NaN
Hong Kong                             48.625000                 47.100000
Hungary                                     NaN                       NaN
Iceland                                     NaN                       NaN
India                                       NaN                       NaN
Iran                                        NaN                       NaN
Ireland                               47.845000                 46.780000
Israel                                50.005000                       NaN
Italy                                 48.618000                 46.861111
Japan                                 49.157143                 46.546667
Lebanon                                     NaN                       NaN
Lithuania                                   NaN                       NaN
Malaysia                                    NaN                       NaN
Mexico                                      NaN                       NaN
Netherlands                           49.963636                 46.656667
New Zealand                                 NaN                 46.515000
Norway                                50.700000                 46.446667
Poland                                      NaN                       NaN
Portugal                                    NaN                 46.480000
Puerto Rico                                 NaN                       NaN
Romania                                     NaN                       NaN
Russia                                      NaN                 46.520000
Saudi Arabia                                NaN                       NaN
Serbia                                      NaN                       NaN
Singapore                             49.320000                       NaN
Slovak Republic                             NaN                       NaN
Slovenia                                    NaN                       NaN
South Africa                          49.575000                 46.680000
South Korea                           49.136667                 47.490000
Spain                                 49.310000                 46.675000
Sweden                                49.306250                 46.456667
Switzerland                           48.184000                 47.930000
Taiwan                                      NaN                 47.065000
Thailand                                    NaN                 46.550000
Turkey                                      NaN                       NaN
USA                                   49.069524                 46.818333
Uganda                                      NaN                       NaN
United Arab Emirates                        NaN                       NaN
United Kingdom                        48.957500                 46.862273
Uruguay                                     NaN                       NaN

                                           max                       \
Rank_Level           First Tier Top University Other Top University
country
Argentina                                  NaN                45.66
Australia                                51.61                45.97
Austria                                    NaN                46.29
Belgium                                  52.03                46.21
Brazil                                     NaN                46.08
Bulgaria                                   NaN                44.48
Canada                                   60.87                45.74
Chile                                      NaN                45.33
China                                    55.30                45.92
Colombia                                   NaN                44.85
Croatia                                    NaN                44.92
Cyprus                                     NaN                44.32
Czech Republic                             NaN                46.23
Denmark                                  52.94                45.83
Egypt                                      NaN                44.52
Estonia                                    NaN                44.94
Finland                                  44.44                45.69
France                                   59.72                45.55
Germany                                  52.75                46.31
Greece                                     NaN                46.06
Hong Kong                                  NaN                45.77
Hungary                                    NaN                45.69
Iceland                                    NaN                45.05
India                                      NaN                46.10
Iran                                       NaN                44.58
Ireland                                    NaN                45.25
Israel                                   66.76                45.76
Italy                                    52.12                46.30
Japan                                    80.64                45.97
Lebanon                                    NaN                44.93
Lithuania                                  NaN                44.46
Malaysia                                   NaN                46.23
Mexico                                     NaN                45.99
Netherlands                              52.42                45.82
New Zealand                                NaN                45.80
Norway                                   50.81                46.31
Poland                                     NaN                45.45
Portugal                                   NaN                45.91
Puerto Rico                                NaN                44.29
Romania                                    NaN                44.32
Russia                                   56.42                45.14
Saudi Arabia                               NaN                45.45
Serbia                                     NaN                44.51
Singapore                                53.52                  NaN
Slovak Republic                            NaN                44.60
Slovenia                                   NaN                45.02
South Africa                               NaN                46.26
South Korea                              66.06                46.23
Spain                                      NaN                46.34
Sweden                                   53.64                46.32
Switzerland                              72.18                45.05
Taiwan                                   54.23                45.49
Thailand                                   NaN                45.86
Turkey                                     NaN                45.57
USA                                     100.00                46.30
Uganda                                     NaN                44.40
United Arab Emirates                       NaN                44.36
United Kingdom                           97.64                46.30
Uruguay                                    NaN                44.35


Rank_Level           Second Tier Top University Third Tier Top University
country
Argentina                                   NaN                       NaN
Australia                                 50.40                     47.47
Austria                                     NaN                     47.78
Belgium                                   49.73                     47.14
Brazil                                    49.82                       NaN
Bulgaria                                    NaN                       NaN
Canada                                    51.23                     47.69
Chile                                       NaN                       NaN
China                                     48.14                     47.76
Colombia                                    NaN                       NaN
Croatia                                     NaN                       NaN
Cyprus                                      NaN                       NaN
Czech Republic                              NaN                     46.32
Denmark                                   50.17                       NaN
Egypt                                       NaN                       NaN
Estonia                                     NaN                       NaN
Finland                                   50.76                       NaN
France                                    50.34                     47.54
Germany                                   50.58                     47.73
Greece                                      NaN                       NaN
Hong Kong                                 49.10                     47.83
Hungary                                     NaN                       NaN
Iceland                                     NaN                       NaN
India                                       NaN                       NaN
Iran                                        NaN                       NaN
Ireland                                   47.96                     46.79
Israel                                    50.89                       NaN
Italy                                     49.97                     47.59
Japan                                     50.13                     47.00
Lebanon                                     NaN                       NaN
Lithuania                                   NaN                       NaN
Malaysia                                    NaN                       NaN
Mexico                                      NaN                       NaN
Netherlands                               51.29                     47.11
New Zealand                                 NaN                     46.65
Norway                                    50.70                     46.67
Poland                                      NaN                       NaN
Portugal                                    NaN                     46.59
Puerto Rico                                 NaN                       NaN
Romania                                     NaN                       NaN
Russia                                      NaN                     46.55
Saudi Arabia                                NaN                       NaN
Serbia                                      NaN                       NaN
Singapore                                 49.35                       NaN
Slovak Republic                             NaN                       NaN
Slovenia                                    NaN                       NaN
South Africa                              50.40                     46.78
South Korea                               50.95                     47.79
Spain                                     50.17                     46.99
Sweden                                    50.34                     46.79
Switzerland                               49.17                     47.93
Taiwan                                      NaN                     47.16
Thailand                                    NaN                     46.55
Turkey                                      NaN                       NaN
USA                                       51.27                     47.82
Uganda                                      NaN                       NaN
United Arab Emirates                        NaN                       NaN
United Kingdom                            49.97                     47.74
Uruguay                                     NaN                       NaN

> Ahora tenemos tanto la media (`mean`) como el máximo (`max`) en las columnas.

### Valores Marginales (`margins`)

Podemos añadir totales generales para resumir los valores de las filas y columnas mediante el parámetro **margins** ajustado a `True`.

Para las columnas de nivel superior (`mean`, `max`), el valor marginal se calculará utilizando la misma función de agregación (es decir, el promedio general para la columna `mean` y el máximo de los máximos para la columna `max`).

In [7]:
df.pivot_table(values='score',
               index='country',
               columns='Rank_Level',
               aggfunc=['mean', 'max'],
               margins=True)

                                          mean                       \
Rank_Level           First Tier Top University Other Top University
country
Argentina                                  NaN            44.672857
Australia                            47.942500            44.645750
Austria                                    NaN            44.864286
Belgium                              51.875000            45.081000
Brazil                                     NaN            44.499706
Bulgaria                                   NaN            44.335000
Canada                               53.633846            44.760541
Chile                                      NaN            44.767500
China                                53.592500            44.564267
Colombia                                   NaN            44.432500
Croatia                                    NaN            44.770000
Cyprus                                     NaN            44.210000
Czech Republic                             NaN            44.587778
Denmark                              49.180000            45.177500
Egypt                                      NaN            44.230000
Estonia                                    NaN            44.810000
Finland                              44.415000            45.062500
France                               51.914444            44.609028
Germany                              49.153636            44.978305
Greece                                     NaN            44.854286
Hong Kong                                  NaN            45.284286
Hungary                                    NaN            44.603333
Iceland                                    NaN            44.980000
India                                      NaN            44.713226
Iran                                       NaN            44.270000
Ireland                                    NaN            44.542500
Israel                               56.307143            45.013333
Italy                                48.736667            44.964177
Japan                                58.812692            44.641583
Lebanon                                    NaN            44.655000
Lithuania                                  NaN            44.355000
Malaysia                                   NaN            45.008333
Mexico                                     NaN            45.102500
Netherlands                          48.378333            45.163333
New Zealand                                NaN            44.832000
Norway                               47.056667            44.950000
Poland                                     NaN            44.497222
Portugal                                   NaN            44.717273
Puerto Rico                                NaN            44.175000
Romania                                    NaN            44.133333
Russia                               51.846667            44.462500
Saudi Arabia                               NaN            44.511250
Serbia                                     NaN            44.420000
Singapore                            50.720000                  NaN
Slovak Republic                            NaN            44.490000
Slovenia                                   NaN            44.615000
South Africa                               NaN            45.246667
South Korea                          55.990000            44.805714
Spain                                      NaN            44.724730
Sweden                               50.672000            45.272500
Switzerland                          54.005000            44.625000
Taiwan                               54.210000            44.476667
Thailand                                   NaN            44.830000
Turkey                                     NaN            44.481000
USA                                  61.066726            44.871718
Uganda                                     NaN            44.280000
United Arab Emirates                       NaN            44.220000
United Kingdom                       63.937931            44.881299
Uruguay                                    NaN            44.255000
All                                  58.350675            44.738871

                                                                           \
Rank_Level           Second Tier Top University Third Tier Top University
country
Argentina                                   NaN                       NaN
Australia                             49.242500                 47.285000
Austria                                     NaN                 47.066667
Belgium                               49.084000                 46.746667
Brazil                                49.565000                       NaN
Bulgaria                                    NaN                       NaN
Canada                                49.218182                 46.826364
Chile                                       NaN                       NaN
China                                 47.868000                 46.926250
Colombia                                    NaN                       NaN
Croatia                                     NaN                       NaN
Cyprus                                      NaN                       NaN
Czech Republic                              NaN                 46.320000
Denmark                               48.965000                       NaN
Egypt                                       NaN                       NaN
Estonia                                     NaN                       NaN
Finland                               50.400000                       NaN
France                                48.888571                 47.125833
Germany                               48.695556                 46.910370
Greece                                      NaN                       NaN
Hong Kong                             48.625000                 47.100000
Hungary                                     NaN                       NaN
Iceland                                     NaN                       NaN
India                                       NaN                       NaN
Iran                                        NaN                       NaN
Ireland                               47.845000                 46.780000
Israel                                50.005000                       NaN
Italy                                 48.618000                 46.861111
Japan                                 49.157143                 46.546667
Lebanon                                     NaN                       NaN
Lithuania                                   NaN                       NaN
Malaysia                                    NaN                       NaN
Mexico                                      NaN                       NaN
Netherlands                           49.963636                 46.656667
New Zealand                                 NaN                 46.515000
Norway                                50.700000                 46.446667
Poland                                      NaN                       NaN
Portugal                                    NaN                 46.480000
Puerto Rico                                 NaN                       NaN
Romania                                     NaN                       NaN
Russia                                      NaN                 46.520000
Saudi Arabia                                NaN                       NaN
Serbia                                      NaN                       NaN
Singapore                             49.320000                       NaN
Slovak Republic                             NaN                       NaN
Slovenia                                    NaN                       NaN
South Africa                          49.575000                 46.680000
South Korea                           49.136667                 47.490000
Spain                                 49.310000                 46.675000
Sweden                                49.306250                 46.456667
Switzerland                           48.184000                 47.930000
Taiwan                                      NaN                 47.065000
Thailand                                    NaN                 46.550000
Turkey                                      NaN                       NaN
USA                                   49.069524                 46.818333
Uganda                                      NaN                       NaN
United Arab Emirates                        NaN                       NaN
United Kingdom                        48.957500                 46.862273
Uruguay                                     NaN                       NaN
All                                   49.065450                 46.843450

                                                      max  \
Rank_Level                  All First Tier Top University
country
Argentina             44.672857                       NaN
Australia             45.825517                     51.61
Austria               45.139583                       NaN
Belgium               47.011000                     52.03
Brazil                44.781111                       NaN
Bulgaria              44.335000                       NaN
Canada                47.359306                     60.87
Chile                 44.767500                       NaN
China                 44.992575                     55.30
Colombia              44.432500                       NaN
Croatia               44.770000                       NaN
Cyprus                44.210000                       NaN
Czech Republic        44.761000                       NaN
Denmark               47.774167                     52.94
Egypt                 44.230000                       NaN
Estonia               44.810000                       NaN
Finland               45.531500                     44.44
France                46.367339                     59.72
Germany               46.413130                     52.75
Greece                44.854286                       NaN
Hong Kong             46.295000                       NaN
Hungary               44.603333                       NaN
Iceland               44.980000                       NaN
India                 44.713226                       NaN
Iran                  44.270000                       NaN
Ireland               45.235000                       NaN
Israel                52.654091                     66.76
Italy                 45.450208                     52.12
Japan                 47.229560                     80.64
Lebanon               44.655000                       NaN
Lithuania             44.355000                       NaN
Malaysia              45.008333                       NaN
Mexico                45.102500                       NaN
Netherlands           47.958276                     52.42
New Zealand           45.112500                       NaN
Norway                46.330000                     50.81
Poland                44.497222                       NaN
Portugal              45.095000                       NaN
Puerto Rico           44.175000                       NaN
Romania               44.133333                       NaN
Russia                47.381111                     56.42
Saudi Arabia          44.511250                       NaN
Serbia                44.420000                       NaN
Singapore             50.160000                     53.52
Slovak Republic       44.490000                       NaN
Slovenia              44.615000                       NaN
South Africa          46.399000                       NaN
South Korea           46.198333                     66.06
Spain                 44.990864                       NaN
Sweden                47.890000                     53.64
Switzerland           51.208846                     72.18
Taiwan                45.012391                     54.23
Thailand              45.116667                       NaN
Turkey                44.481000                       NaN
USA                   51.839860                    100.00
Uganda                44.280000                       NaN
United Arab Emirates  44.220000                       NaN
United Kingdom        49.474653                     97.64
Uruguay               44.255000                       NaN
All                   47.798395                    100.00

                                                                      \
Rank_Level           Other Top University Second Tier Top University
country
Argentina                           45.66                        NaN
Australia                           45.97                      50.40
Austria                             46.29                        NaN
Belgium                             46.21                      49.73
Brazil                              46.08                      49.82
Bulgaria                            44.48                        NaN
Canada                              45.74                      51.23
Chile                               45.33                        NaN
China                               45.92                      48.14
Colombia                            44.85                        NaN
Croatia                             44.92                        NaN
Cyprus                              44.32                        NaN
Czech Republic                      46.23                        NaN
Denmark                             45.83                      50.17
Egypt                               44.52                        NaN
Estonia                             44.94                        NaN
Finland                             45.69                      50.76
France                              45.55                      50.34
Germany                             46.31                      50.58
Greece                              46.06                        NaN
Hong Kong                           45.77                      49.10
Hungary                             45.69                        NaN
Iceland                             45.05                        NaN
India                               46.10                        NaN
Iran                                44.58                        NaN
Ireland                             45.25                      47.96
Israel                              45.76                      50.89
Italy                               46.30                      49.97
Japan                               45.97                      50.13
Lebanon                             44.93                        NaN
Lithuania                           44.46                        NaN
Malaysia                            46.23                        NaN
Mexico                              45.99                        NaN
Netherlands                         45.82                      51.29
New Zealand                         45.80                        NaN
Norway                              46.31                      50.70
Poland                              45.45                        NaN
Portugal                            45.91                        NaN
Puerto Rico                         44.29                        NaN
Romania                             44.32                        NaN
Russia                              45.14                        NaN
Saudi Arabia                        45.45                        NaN
Serbia                              44.51                        NaN
Singapore                             NaN                      49.35
Slovak Republic                     44.60                        NaN
Slovenia                            45.02                        NaN
South Africa                        46.26                      50.40
South Korea                         46.23                      50.95
Spain                               46.34                      50.17
Sweden                              46.32                      50.34
Switzerland                         45.05                      49.17
Taiwan                              45.49                        NaN
Thailand                            45.86                        NaN
Turkey                              45.57                        NaN
USA                                 46.30                      51.27
Uganda                              44.40                        NaN
United Arab Emirates                44.36                        NaN
United Kingdom                      46.30                      49.97
Uruguay                             44.35                        NaN
All                                 46.34                      51.29


Rank_Level           Third Tier Top University     All
country
Argentina                                  NaN   45.66
Australia                                47.47   51.61
Austria                                  47.78   47.78
Belgium                                  47.14   52.03
Brazil                                     NaN   49.82
Bulgaria                                   NaN   44.48
Canada                                   47.69   60.87
Chile                                      NaN   45.33
China                                    47.76   55.30
Colombia                                   NaN   44.85
Croatia                                    NaN   44.92
Cyprus                                     NaN   44.32
Czech Republic                           46.32   46.32
Denmark                                    NaN   52.94
Egypt                                      NaN   44.52
Estonia                                    NaN   44.94
Finland                                    NaN   50.76
France                                   47.54   59.72
Germany                                  47.73   52.75
Greece                                     NaN   46.06
Hong Kong                                47.83   49.10
Hungary                                    NaN   45.69
Iceland                                    NaN   45.05
India                                      NaN   46.10
Iran                                       NaN   44.58
Ireland                                  46.79   47.96
Israel                                     NaN   66.76
Italy                                    47.59   52.12
Japan                                    47.00   80.64
Lebanon                                    NaN   44.93
Lithuania                                  NaN   44.46
Malaysia                                   NaN   46.23
Mexico                                     NaN   45.99
Netherlands                              47.11   52.42
New Zealand                              46.65   46.65
Norway                                   46.67   50.81
Poland                                     NaN   45.45
Portugal                                 46.59   46.59
Puerto Rico                                NaN   44.29
Romania                                    NaN   44.32
Russia                                   46.55   56.42
Saudi Arabia                               NaN   45.45
Serbia                                     NaN   44.51
Singapore                                  NaN   53.52
Slovak Republic                            NaN   44.60
Slovenia                                   NaN   45.02
South Africa                             46.78   50.40
South Korea                              47.79   66.06
Spain                                    46.99   50.17
Sweden                                   46.79   53.64
Switzerland                              47.93   72.18
Taiwan                                   47.16   54.23
Thailand                                 46.55   46.55
Turkey                                     NaN   45.57
USA                                      47.82  100.00
Uganda                                     NaN   44.40
United Arab Emirates                       NaN   44.36
United Kingdom                           47.74   97.64

> En la columna **'All'** de cada fila ahora se proporcionan los totales generales (agregaciones).

### Consulta de Datos en Tablas Pivot Jerárquicas

Una tabla pivot es solo un **DataFrame de múltiples niveles** (MultiIndex). Por lo tanto, podemos acceder a sus datos de forma similar a un DataFrame regular.

In [8]:
new_df = df.pivot_table(values='score',
                        index='country',
                        columns='Rank_Level',
                        aggfunc=['mean', 'max'],
                        margins=True)

# Veamos el índice
new_df.index

Index(['Argentina', 'Australia', 'Austria', 'Belgium', 'Brazil', 'Bulgaria',
       'Canada', 'Chile', 'China', 'Colombia', 'Croatia', 'Cyprus',
       'Czech Republic', 'Denmark', 'Egypt', 'Estonia', 'Finland', 'France',
       'Germany', 'Greece', 'Hong Kong', 'Hungary', 'Iceland', 'India', 'Iran',
       'Ireland', 'Israel', 'Italy', 'Japan', 'Lebanon', 'Lithuania',
       'Malaysia', 'Mexico', 'Netherlands', 'New Zealand', 'Norway', 'Poland',
       'Portugal', 'Puerto Rico', 'Romania', 'Russia', 'Saudi Arabia',
       'Serbia', 'Singapore', 'Slovak Republic', 'Slovenia', 'South Africa',
       'South Korea', 'Spain', 'Sweden', 'Switzerland', 'Taiwan', 'Thailand',
       'Turkey', 'USA', 'Uganda', 'United Arab Emirates', 'United Kingdom',
       'Uruguay', 'All'],
      dtype='object', name='country')

In [9]:
# Columnas
new_df.columns

MultiIndex([('mean',  'First Tier Top University'),
            ('mean',       'Other Top University'),
            ('mean', 'Second Tier Top University'),
            ('mean',  'Third Tier Top University'),
            ('mean',                        'All'),
            ( 'max',  'First Tier Top University'),
            ( 'max',       'Other Top University'),
            ( 'max', 'Second Tier Top University'),
            ( 'max',  'Third Tier Top University'),
            ( 'max',                        'All')],
           names=[None, 'Rank_Level'])

Para obtener los valores **promedio** (`mean`) de las universidades de **Primer Nivel** (`First Tier Top University`) en cada país, realizamos una doble proyección:

In [10]:
new_df['mean']['First Tier Top University']

country
Argentina                     NaN
Australia               47.942500
Austria                       NaN
Belgium                 51.875000
Brazil                        NaN
Bulgaria                      NaN
Canada                  53.633846
Chile                         NaN
China                   53.592500
Colombia                      NaN
Croatia                       NaN
Cyprus                        NaN
Czech Republic                NaN
Denmark                 49.180000
Egypt                         NaN
Estonia                       NaN
Finland                 44.415000
France                  51.914444
Germany                 49.153636
Greece                        NaN
Hong Kong                     NaN
Hungary                       NaN
Iceland                       NaN
India                         NaN
Iran                          NaN
Ireland                       NaN
Israel                  56.307143
Italy                   48.736667
Japan                   58.812692
Lebanon                       NaN
Lithuania                     NaN
Malaysia                      NaN
Mexico                        NaN
Netherlands             48.378333
New Zealand                   NaN
Norway                  47.056667
Poland                        NaN
Portugal                      NaN
Puerto Rico                   NaN
Romania                       NaN
Russia                  51.846667
Saudi Arabia                  NaN
Serbia                        NaN
Singapore               50.720000
Slovak Republic               NaN
Slovenia                      NaN
South Africa                  NaN
South Korea             55.990000
Spain                         NaN
Sweden                  50.672000
Switzerland             54.005000
Taiwan                  54.210000
Thailand                      NaN
Turkey                        NaN
USA                     61.066726
Uganda                        NaN
United Arab Emirates          NaN
United Kingdom          63.937931
Uruguay                       NaN
All                     58.350675
Name: First Tier Top University, dtype: float64

El resultado es un objeto **Series**, lo que podemos confirmar con la función `type()`

In [11]:
type(new_df['mean']['First Tier Top University'])

pandas.core.series.Series

#### Encontrar el País con el Máximo Promedio

Podemos usar la función **`idxmax()`** para encontrar el índice (en este caso, el país) que tiene el máximo valor en la Serie de promedios de "First Tier Top University".

In [12]:
new_df['mean']['First Tier Top University'].idxmax()

'United Kingdom'

### Reestructuración con `stack()` y `unstack()`

Las funciones `stack()` y `unstack()` nos permiten cambiar la forma de la tabla pivote.

  * **`stack()`**: Pivota (intercambia) el índice de columna de nivel más bajo para que se convierta en el índice de fila más interno.
  * **`unstack()`**: Es la operación inversa, pívota el índice de fila más interno para que se convierta en el índice de columna de nivel más bajo.

#### Usando `stack()`

Veamos la forma original de nuestro DataFrame pivot antes de aplicar `stack()`:

In [13]:
new_df.head()

                                mean                       \
Rank_Level First Tier Top University Other Top University
country
Argentina                        NaN            44.672857
Australia                    47.9425            44.645750
Austria                          NaN            44.864286
Belgium                      51.8750            45.081000
Brazil                           NaN            44.499706

                                                                            \
Rank_Level Second Tier Top University Third Tier Top University        All
country
Argentina                         NaN                       NaN  44.672857
Australia                     49.2425                 47.285000  45.825517
Austria                           NaN                 47.066667  45.139583
Belgium                       49.0840                 46.746667  47.011000
Brazil                        49.5650                       NaN  44.781111

                                 max                       \
Rank_Level First Tier Top University Other Top University
country
Argentina                        NaN                45.66
Australia                      51.61                45.97
Austria                          NaN                46.29
Belgium                        52.03                46.21
Brazil                           NaN                46.08


Rank_Level Second Tier Top University Third Tier Top University    All
country
Argentina                         NaN                       NaN  45.66
Australia                       50.40                     47.47  51.61
Austria                           NaN                     47.78  47.78
Belgium                         49.73                     47.14  52.03
Brazil                          49.82                       NaN  49.82

Al aplicar `stack()`, el nivel de columna más bajo (`Rank_Level`) se convierte en el índice de fila más interno, a la derecha de `country`.

In [14]:
new_df = new_df.stack(future_stack=True)

new_df.head()

                                           mean    max
country   Rank_Level
Argentina First Tier Top University         NaN    NaN
          Other Top University        44.672857  45.66
          Second Tier Top University        NaN    NaN
          Third Tier Top University         NaN    NaN
          All                         44.672857  45.66

#### Usando `unstack()`

Al aplicar `unstack()` en el DataFrame apilado, restauramos su forma original, moviendo el índice de fila más interno (`Rank_Level`) de vuelta a las columnas.

In [15]:
new_df.unstack().head()

                                mean                       \
Rank_Level First Tier Top University Other Top University
country
Argentina                        NaN            44.672857
Australia                    47.9425            44.645750
Austria                          NaN            44.864286
Belgium                      51.8750            45.081000
Brazil                           NaN            44.499706

                                                                            \
Rank_Level Second Tier Top University Third Tier Top University        All
country
Argentina                         NaN                       NaN  44.672857
Australia                     49.2425                 47.285000  45.825517
Austria                           NaN                 47.066667  45.139583
Belgium                       49.0840                 46.746667  47.011000
Brazil                        49.5650                       NaN  44.781111

                                 max                       \
Rank_Level First Tier Top University Other Top University
country
Argentina                        NaN                45.66
Australia                      51.61                45.97
Austria                          NaN                46.29
Belgium                        52.03                46.21
Brazil                           NaN                46.08


Rank_Level Second Tier Top University Third Tier Top University    All
country
Argentina                         NaN                       NaN  45.66
Australia                       50.40                     47.47  51.61
Austria                           NaN                     47.78  47.78
Belgium                         49.73                     47.14  52.03
Brazil                          49.82                       NaN  49.82

Al realizar **`unstack()`** dos veces seguidas, se despliegan todos los niveles jerárquicos de las filas en las columnas, dando como resultado un objeto **Series** con un MultiIndex complejo, pero con una sola columna de valores:

In [16]:
new_df.unstack().unstack().head()

      Rank_Level                 country
mean  First Tier Top University  Argentina        NaN
                                 Australia    47.9425
                                 Austria          NaN
                                 Belgium      51.8750
                                 Brazil           NaN
dtype: float64

## Conclusión

Las tablas pivot son increíblemente útiles para trabajar con datos numéricos, especialmente al intentar **resumir los datos** de alguna forma.

Normalmente, crearás nuevas tablas pivot en secciones de datos, ya sea que estés explorando los datos o preparando datos para reportes.

Recuerda que puedes pasar **cualquier función** al parámetro `aggfunc`, incluidas las que definas tú mismo.